In [13]:
import ast
import pandas as pd

In [14]:
routes_hard =[]

with open ('hard_route.txt', 'r', encoding='utf8') as f:
    routes_hard = f.read()

In [15]:
routes_list = ast.literal_eval(routes_hard)
pd.DataFrame(routes_list)

,route_id,vehicle,weight,routes,driver_cost,fuel_cost,goods_cost,total_cost,travel_hours,travel_kms
0,company_1_DESTINATION_TEST,66LD 94467,20,"[[261 KP. 3, QL. 1A, TT. Bến Lức, H. Bến Lức, ...",48000.0,0.000000e+00,22084.270111,7.008427e+04,0.00,0.0
1,company_1_DESTINATION_TEST,51LD 38199,18,"[[261 KP. 3, QL. 1A, TT. Bến Lức, H. Bến Lức, ...",101280.0,5.486739e+08,19875.843100,5.487950e+08,2.22,845.0
2,company_1_DESTINATION_TEST,66LD 93106,15,"[[261 KP. 3, QL. 1A, TT. Bến Lức, H. Bến Lức, ...",101280.0,5.486739e+08,16563.202583,5.487917e+08,2.22,845.0
3,company_1_DESTINATION_TEST,53LD 10175,9,"[[261 KP. 3, QL. 1A, TT. Bến Lức, H. Bến Lức, ...",101280.0,5.486739e+08,9937.921550,5.487851e+08,2.22,845.0
4,company_1_DESTINATION_TEST,68LD 67509,8,"[[261 KP. 3, QL. 1A, TT. Bến Lức, H. Bến Lức, ...",101280.0,5.486739e+08,8833.708044,5.487840e+08,2.22,845.0
...,...,...,...,...,...,...,...,...,...,...
145,company_30_DESTINATION_TEST,66LD 94467,20,"[[ấp 3, X. Nhị Thành, H. Thủ Thừa, Long An, ĐT...",102000.0,5.480245e+08,71717.055620,5.481983e+08,2.25,844.0
146,company_30_DESTINATION_TEST,51LD 38199,18,"[[ấp 3, X. Nhị Thành, H. Thủ Thừa, Long An, ĐT...",102000.0,5.480245e+08,64545.350058,5.481911e+08,2.25,844.0
147,company_30_DESTINATION_TEST,66LD 93106,15,"[[ấp 3, X. Nhị Thành, H. Thủ Thừa, Long An, ĐT...",102000.0,5.480245e+08,53787.791715,5.481803e+08,2.25,844.0
148,company_30_DESTINATION_TEST,53LD 10175,9,"[[ấp 3, X. Nhị Thành, H. Thủ Thừa, Long An, ĐT...",102000.0,5.480245e+08,32272.675029,5.481588e+08,2.25,844.0
149,company_30_DESTINATION_TEST,68LD 67509,8,"[[ấp 3, X. Nhị Thành, H. Thủ Thừa, Long An, ĐT...",102000.0,5.480245e+08,28686.822248,5.481552e+08,2.25,844.0